package com.example.SpringCommerceShop.Modal;

public class AccountKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.id_user
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	private String idUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.username
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	private String username;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.id_user
	 * @return  the value of account.id_user
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public String getIdUser() {
		return idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.id_user
	 * @param idUser  the value for account.id_user
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.username
	 * @return  the value of account.username
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.username
	 * @param username  the value for account.username
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public void setUsername(String username) {
		this.username = username;
	}
}