package com.example.SpringCommerceShop.Modal;

public class Account {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.id_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String idUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.name_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String nameUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.username
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.password
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.role
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private Integer role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.id_user
	 * @return  the value of account.id_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getIdUser() {
		return idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.id_user
	 * @param idUser  the value for account.id_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.name_user
	 * @return  the value of account.name_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getNameUser() {
		return nameUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.name_user
	 * @param nameUser  the value for account.name_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setNameUser(String nameUser) {
		this.nameUser = nameUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.username
	 * @return  the value of account.username
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.username
	 * @param username  the value for account.username
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.password
	 * @return  the value of account.password
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.password
	 * @param password  the value for account.password
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.role
	 * @return  the value of account.role
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.role
	 * @param role  the value for account.role
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setRole(Integer role) {
		this.role = role;
	}
}