package com.example.SpringCommerceShop.Modal;

public class Account extends AccountKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.name_user
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	private String idUser;
	private String username;
	private String nameUser;

	@Override
	public String getIdUser() {
		return idUser;
	}

	@Override
	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	@Override
	public String getUsername() {
		return username;
	}

	@Override
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.password
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.role
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	private Integer role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.name_user
	 * @return  the value of account.name_user
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public String getNameUser() {
		return nameUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.name_user
	 * @param nameUser  the value for account.name_user
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public void setNameUser(String nameUser) {
		this.nameUser = nameUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.password
	 * @return  the value of account.password
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.password
	 * @param password  the value for account.password
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.role
	 * @return  the value of account.role
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.role
	 * @param role  the value for account.role
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	public Account(String idUser, String nameUser, String username, String password, Integer role) {
		this.idUser = idUser;
		this.nameUser = nameUser;
		this.username = username;
		this.password = password;
		this.role = role;
	}
}