package com.example.SpringCommerceShop.Modal;

public class orders_products extends orders_productsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders_products.quantity
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	private Integer quantity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders_products.quantity
	 * @return  the value of orders_products.quantity
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders_products.quantity
	 * @param quantity  the value for orders_products.quantity
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
}