package com.example.SpringCommerceShop.Modal;

public class orders_productsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders_products.id
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders_products.id_order
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	private String idOrder;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders_products.id
	 * @return  the value of orders_products.id
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders_products.id
	 * @param id  the value for orders_products.id
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders_products.id_order
	 * @return  the value of orders_products.id_order
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public String getIdOrder() {
		return idOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders_products.id_order
	 * @param idOrder  the value for orders_products.id_order
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	public void setIdOrder(String idOrder) {
		this.idOrder = idOrder;
	}
}