package com.example.SpringCommerceShop.Modal;

public class Orders {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.id_order
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String idOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.name_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String nameUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.address
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.phone
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.email_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private String emailUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.total_price
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	private Integer totalPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.id_order
	 * @return  the value of orders.id_order
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getIdOrder() {
		return idOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.id_order
	 * @param idOrder  the value for orders.id_order
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setIdOrder(String idOrder) {
		this.idOrder = idOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.name_user
	 * @return  the value of orders.name_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getNameUser() {
		return nameUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.name_user
	 * @param nameUser  the value for orders.name_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setNameUser(String nameUser) {
		this.nameUser = nameUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.address
	 * @return  the value of orders.address
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.address
	 * @param address  the value for orders.address
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.phone
	 * @return  the value of orders.phone
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.phone
	 * @param phone  the value for orders.phone
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.email_user
	 * @return  the value of orders.email_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public String getEmailUser() {
		return emailUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.email_user
	 * @param emailUser  the value for orders.email_user
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setEmailUser(String emailUser) {
		this.emailUser = emailUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.total_price
	 * @return  the value of orders.total_price
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public Integer getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.total_price
	 * @param totalPrice  the value for orders.total_price
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	public void setTotalPrice(Integer totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Orders(String idOrder, String nameUser, String address, String phone, String emailUser, int totalPrice) {
		super();
		this.idOrder = idOrder;
		this.nameUser = nameUser;
		this.address = address;
		this.phone = phone;
		this.emailUser = emailUser;
		this.totalPrice = totalPrice;
	}
}