package com.example.SpringCommerceShop.Modal;

public class ProductWithBLOBs extends Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img
     *
     * @return the value of product.img
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img
     *
     * @param img the value for product.img
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public void setImg(String img) {
        this.img = img;
    }
}