package com.example.SpringCommerceShop.Modal;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.color
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    private String brand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category
     *
     * @return the value of product.category
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category
     *
     * @param category the value for product.category
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.color
     *
     * @return the value of product.color
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.color
     *
     * @param color the value for product.color
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand
     *
     * @return the value of product.brand
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand
     *
     * @param brand the value for product.brand
     *
     * @mbg.generated Sun Apr 02 00:23:29 ICT 2023
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }
}