package com.example.SpringCommerceShop.Mapper;

import com.example.SpringCommerceShop.Modal.Account;
import com.example.SpringCommerceShop.Modal.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	long countByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	int deleteByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	int deleteByPrimaryKey(String idUser);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	int insert(Account row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	int insertSelective(Account row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	List<Account> selectByExample(AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	Account selectByPrimaryKey(String idUser);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") Account row, @Param("example") AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	int updateByExample(@Param("row") Account row, @Param("example") AccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	int updateByPrimaryKeySelective(Account row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account
	 * @mbg.generated  Sun Apr 02 00:23:29 ICT 2023
	 */
	int updateByPrimaryKey(Account row);
}