package com.example.SpringCommerceShop.Mapper;

import com.example.SpringCommerceShop.Modal.Orders;
import com.example.SpringCommerceShop.Modal.OrdersExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface OrdersMapper {

	
	
//	void insertOrder(Orders orders);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	long countByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	int deleteByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	int deleteByPrimaryKey(String idOrder);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	int insert(Orders row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	int insertSelective(Orders row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	List<Orders> selectByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	Orders selectByPrimaryKey(String idOrder);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") Orders row, @Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	int updateByExample(@Param("row") Orders row, @Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	int updateByPrimaryKeySelective(Orders row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sat Apr 08 02:56:38 ICT 2023
	 */
	int updateByPrimaryKey(Orders row);

	void insertOrder(Orders orders);
}