package com.example.SpringCommerceShop.Mapper;

import com.example.SpringCommerceShop.Modal.orders_products;
import com.example.SpringCommerceShop.Modal.orders_productsExample;
import com.example.SpringCommerceShop.Modal.orders_productsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface orders_productsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	long countByExample(orders_productsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int deleteByExample(orders_productsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int deleteByPrimaryKey(orders_productsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int insert(orders_products row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int insertSelective(orders_products row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	List<orders_products> selectByExample(orders_productsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	orders_products selectByPrimaryKey(orders_productsKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") orders_products row, @Param("example") orders_productsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByExample(@Param("row") orders_products row, @Param("example") orders_productsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByPrimaryKeySelective(orders_products row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders_products
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByPrimaryKey(orders_products row);
}