package com.example.SpringCommerceShop.Mapper;

import com.example.SpringCommerceShop.Modal.MyPageInfo;
import com.example.SpringCommerceShop.Modal.Product;
import com.example.SpringCommerceShop.Modal.ProductExample;
import com.example.SpringCommerceShop.Modal.ProductWithBLOBs;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ProductMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	long countByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int insert(ProductWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int insertSelective(ProductWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	List<ProductWithBLOBs> selectByExampleWithBLOBs(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	List<Product> selectByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	ProductWithBLOBs selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") ProductWithBLOBs row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByExampleWithBLOBs(@Param("row") ProductWithBLOBs row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByExample(@Param("row") Product row, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByPrimaryKeySelective(ProductWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByPrimaryKeyWithBLOBs(ProductWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Sun Apr 09 12:47:54 ICT 2023
	 */
	int updateByPrimaryKey(Product row);

	//    List<Map<String, Object>> getAllProduct (Map<String, Object> param);
    List<Map<String, Object>> getAllProduct();
    
    List<Map<String, Object>> getProductPage(MyPageInfo pageInfo);
    
    int getCountProduct();
    
  
    List<Map<String, Object>> findByID(String idInput);
    List<Map<String, Object>> findByName(String nameInput);
    List<Map<String, Object>> findByCategory(int category);

    
}